
services:
  app:
    build: .
    ports:
      - "${APP_PORT:-5436}:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST:-postgres}:${DB_PORT:-5432}/${DB_NAME:-app_db}
      SPRING_DATASOURCE_USERNAME: ${DB_USER:-app_user}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-app_password}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${JPA_DDL_AUTO:-update}
      SPRING_JPA_SHOW_SQL: ${JPA_SHOW_SQL:-true}

      JWT_SECRET: ${JWT_SECRET:-mySuperSecretJwtKeyChangeInProduction}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS:-86400000}

      SERVER_PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:-app_db}
      POSTGRES_USER: ${DB_USER:-app_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-app_password}
    ports:
      - "${DB_PORT_HOST:-5435}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB_USER:-app_user} -d $${DB_NAME:-app_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
    postgres_data:
      driver: local
